using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.ExtensibleStorage;

namespace JarviTools.Commands.MaintenanceReachability
{
    /// <summary>
    /// Values shown to ordinary Revit users for one maintenance-preview DirectShape.
    /// Six fields are generated by the plug-in. MaintenanceConclusion and
    /// ProfessionalNote are user-editable and are kept when their value is null, so a
    /// regeneration need not erase professional confirmation already entered in Revit.
    /// </summary>
    public sealed class MaintenanceParameterValues
    {
        public string ElementName { get; set; }
        public string CeilingGroup { get; set; }
        public string EntryGroup { get; set; }
        public string ElementRole { get; set; }
        public string MaintenanceTarget { get; set; }
        public string MaintenanceConclusion { get; set; }
        public string DecisionNote { get; set; }
        public string ProfessionalNote { get; set; }
    }

    /// <summary>
    /// Shared-parameter binding, DirectShape labelling and view-filter presentation for
    /// maintenance reachability output.  Public mutating methods must be called inside
    /// a caller-owned Revit transaction; the service never starts a nested transaction.
    /// </summary>
    public static class MaintenanceParameterService
    {
        public const string SharedParameterFileName = "OpenRevit维修可达共享参数.txt";
        public const string ParameterGroupName = "CODEX_维修可达";
        public const string ResourcePrefix = "CODEX_OpenRevit_维修可达_v1_";
        private const string LegacyResourcePrefix = "CODEX_维修可达_";
        private const string ResourceOwnerId = "OpenRevit.Tools.MaintenanceReachability.v1";
        private static readonly Guid ResourceOwnershipSchemaGuid =
            new Guid("86f4538f-0219-4ac2-81f9-e95e821e09bc");

        public const string ParameterElementName = "CODEX_构件名称";
        public const string ParameterCeilingGroup = "CODEX_天花分组";
        public const string ParameterEntryGroup = "CODEX_入口组";
        public const string ParameterElementRole = "CODEX_构件角色";
        public const string ParameterMaintenanceTarget = "CODEX_维修对象";
        public const string ParameterMaintenanceConclusion = "CODEX_维修结论";
        public const string ParameterDecisionNote = "CODEX_判断说明";
        public const string ParameterProfessionalNote = "CODEX_专业备注";

        public const string ConclusionPending = "待确认";
        public const string ConclusionMaintainable = "可维修";
        public const string ConclusionNotMaintainable = "不可维修";
        public const string ConclusionError = "异常";

        public static readonly Guid ElementNameGuid = new Guid("85edc0dd-1e31-4a61-8ca6-1349013868fc");
        public static readonly Guid CeilingGroupGuid = new Guid("0bab88cb-a091-490b-83cc-39ac57c36d93");
        public static readonly Guid EntryGroupGuid = new Guid("8005d104-8fb7-4f04-9547-21f974329afb");
        public static readonly Guid ElementRoleGuid = new Guid("997a8f20-be94-4baa-87a8-f70e0781d9de");
        public static readonly Guid MaintenanceTargetGuid = new Guid("95598591-f7a7-42d1-a902-1bee0e67c026");
        public static readonly Guid MaintenanceConclusionGuid = new Guid("6591fc5e-eabd-4b28-95d8-86adf6dda5d4");
        public static readonly Guid DecisionNoteGuid = new Guid("7c412708-2d65-4b54-bdd1-275a3fc14188");
        public static readonly Guid ProfessionalNoteGuid = new Guid("89d3fa95-7d87-40c0-b4f8-234bc891b09c");

        private sealed class ParameterSpec
        {
            public string Name;
            public Guid Guid;
            public bool UserModifiable;
            public string Description;
        }

        private sealed class FilterSpec
        {
            public string Name;
            public Guid ParameterGuid;
            public string MatchValue;
            public bool Contains;
            public Color Color;
            public bool IsConclusion;
            public bool FillSurfaces;
            public int Transparency;
        }

        private sealed class MaterialSpec
        {
            public string Name;
            public Color Color;
            public int Transparency;
        }

        private static readonly ParameterSpec[] ParameterSpecs =
        {
            new ParameterSpec { Name = ParameterElementName, Guid = ElementNameGuid, UserModifiable = false, Description = "用户可读的维修可达构件名称" },
            new ParameterSpec { Name = ParameterCeilingGroup, Guid = CeilingGroupGuid, UserModifiable = false, Description = "维修可达结果所属天花逻辑分组" },
            new ParameterSpec { Name = ParameterEntryGroup, Guid = EntryGroupGuid, UserModifiable = false, Description = "同一套入口、梯子、路线和维修区的组号" },
            new ParameterSpec { Name = ParameterElementRole, Guid = ElementRoleGuid, UserModifiable = false, Description = "检修门、梯子、路线、转身区或维修区等构件角色" },
            new ParameterSpec { Name = ParameterMaintenanceTarget, Guid = MaintenanceTargetGuid, UserModifiable = false, Description = "面向用户的设备类型与标记，不包含内部图元 ID" },
            new ParameterSpec { Name = ParameterMaintenanceConclusion, Guid = MaintenanceConclusionGuid, UserModifiable = true, Description = "待确认、可维修、不可维修或异常" },
            new ParameterSpec { Name = ParameterDecisionNote, Guid = DecisionNoteGuid, UserModifiable = false, Description = "维修可达性判断的简明原因" },
            new ParameterSpec { Name = ParameterProfessionalNote, Guid = ProfessionalNoteGuid, UserModifiable = true, Description = "供专业施工单位确认或补充" }
        };

        private static readonly FilterSpec[] FilterSpecs =
        {
            // Role filters control outlines; conclusion filters control filled surfaces.
            // Keeping these graphic channels separate makes both classifications legible.
            new FilterSpec { Name = ResourcePrefix + "角色_虚拟边界墙", ParameterGuid = ElementRoleGuid, MatchValue = "虚拟边界墙", Contains = true, Color = new Color(125, 135, 150), IsConclusion = false, FillSurfaces = true, Transparency = 88 },
            new FilterSpec { Name = ResourcePrefix + "角色_检修门", ParameterGuid = ElementRoleGuid, MatchValue = "检修门", Contains = true, Color = new Color(30, 180, 255), IsConclusion = false, FillSurfaces = true, Transparency = 8 },
            new FilterSpec { Name = ResourcePrefix + "角色_检修口", ParameterGuid = ElementRoleGuid, MatchValue = "检修口", Contains = true, Color = new Color(30, 180, 255), IsConclusion = false, FillSurfaces = true, Transparency = 8 },
            new FilterSpec { Name = ResourcePrefix + "角色_梯子", ParameterGuid = ElementRoleGuid, MatchValue = "梯", Contains = true, Color = new Color(195, 205, 215), IsConclusion = false, FillSurfaces = true, Transparency = 5 },
            new FilterSpec { Name = ResourcePrefix + "角色_路线", ParameterGuid = ElementRoleGuid, MatchValue = "路线", Contains = true, Color = new Color(0, 235, 235), IsConclusion = false, FillSurfaces = true, Transparency = 18 },
            new FilterSpec { Name = ResourcePrefix + "角色_通行包络", ParameterGuid = ElementRoleGuid, MatchValue = "通行包络", Contains = true, Color = new Color(0, 220, 245), IsConclusion = false, FillSurfaces = true, Transparency = 24 },
            new FilterSpec { Name = ResourcePrefix + "角色_转身区", ParameterGuid = ElementRoleGuid, MatchValue = "转身", Contains = true, Color = new Color(45, 225, 125), IsConclusion = false, FillSurfaces = true, Transparency = 26 },
            new FilterSpec { Name = ResourcePrefix + "角色_伸手通道", ParameterGuid = ElementRoleGuid, MatchValue = "伸手通道", Contains = true, Color = new Color(255, 155, 25), IsConclusion = false, FillSurfaces = true, Transparency = 35 },
            new FilterSpec { Name = ResourcePrefix + "角色_检修面代理点", ParameterGuid = ElementRoleGuid, MatchValue = "检修面代理点", Contains = true, Color = new Color(235, 70, 220), IsConclusion = false, FillSurfaces = true, Transparency = 20 },
            new FilterSpec { Name = ResourcePrefix + "角色_维修区", ParameterGuid = ElementRoleGuid, MatchValue = "维修区", Contains = true, Color = new Color(195, 70, 255), IsConclusion = false, FillSurfaces = false, Transparency = 0 },
            new FilterSpec { Name = ResourcePrefix + "角色_维修对象", ParameterGuid = ElementRoleGuid, MatchValue = "维修对象", Contains = true, Color = new Color(245, 80, 225), IsConclusion = false, FillSurfaces = true, Transparency = 12 },
            new FilterSpec { Name = ResourcePrefix + "结论_待确认", ParameterGuid = MaintenanceConclusionGuid, MatchValue = ConclusionPending, Contains = false, Color = new Color(255, 215, 0), IsConclusion = true },
            new FilterSpec { Name = ResourcePrefix + "结论_可维修", ParameterGuid = MaintenanceConclusionGuid, MatchValue = ConclusionMaintainable, Contains = false, Color = new Color(35, 210, 95), IsConclusion = true },
            new FilterSpec { Name = ResourcePrefix + "结论_不可维修", ParameterGuid = MaintenanceConclusionGuid, MatchValue = ConclusionNotMaintainable, Contains = false, Color = new Color(235, 45, 55), IsConclusion = true },
            new FilterSpec { Name = ResourcePrefix + "结论_异常", ParameterGuid = MaintenanceConclusionGuid, MatchValue = ConclusionError, Contains = false, Color = new Color(245, 0, 205), IsConclusion = true }
        };

        private static readonly MaterialSpec[] MaterialSpecs =
        {
            new MaterialSpec { Name = ResourcePrefix + "材质_待确认", Color = new Color(255, 215, 0), Transparency = 15 },
            new MaterialSpec { Name = ResourcePrefix + "材质_可维修", Color = new Color(35, 210, 95), Transparency = 15 },
            new MaterialSpec { Name = ResourcePrefix + "材质_不可维修", Color = new Color(235, 45, 55), Transparency = 10 },
            new MaterialSpec { Name = ResourcePrefix + "材质_异常", Color = new Color(245, 0, 205), Transparency = 10 },
            new MaterialSpec { Name = ResourcePrefix + "材质_检修门", Color = new Color(0, 205, 255), Transparency = 20 },
            new MaterialSpec { Name = ResourcePrefix + "材质_梯子", Color = new Color(30, 165, 255), Transparency = 10 },
            new MaterialSpec { Name = ResourcePrefix + "材质_路线", Color = new Color(0, 235, 235), Transparency = 25 },
            new MaterialSpec { Name = ResourcePrefix + "材质_转身区", Color = new Color(45, 225, 125), Transparency = 35 },
            new MaterialSpec { Name = ResourcePrefix + "材质_维修区", Color = new Color(195, 70, 255), Transparency = 25 }
        };

        public static string GetDefaultSharedParameterFilePath()
        {
            string assemblyFolder = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            return Path.Combine(assemblyFolder ?? string.Empty, "Resources", SharedParameterFileName);
        }

        /// <summary>
        /// Ensures all eight shared parameters exist as Generic Model instance parameters.
        /// Existing bindings are identified by GUID, not name.  An existing instance binding
        /// is widened to Generic Models without dropping any previously bound category.
        /// </summary>
        public static void EnsureSharedParameters(Document doc, string sharedParameterFilePath)
        {
            RequireModifiableDocument(doc);
            if (string.IsNullOrWhiteSpace(sharedParameterFilePath) || !File.Exists(sharedParameterFilePath))
                throw new FileNotFoundException("找不到维修可达共享参数文件。", sharedParameterFilePath);

            string originalFile = doc.Application.SharedParametersFilename;
            try
            {
                doc.Application.SharedParametersFilename = sharedParameterFilePath;
                DefinitionFile definitionFile = doc.Application.OpenSharedParameterFile();
                if (definitionFile == null)
                    throw new InvalidOperationException("无法打开维修可达共享参数文件：" + sharedParameterFilePath);

                foreach (ParameterSpec spec in ParameterSpecs)
                {
                    ExternalDefinition fileDefinition = FindExternalDefinition(definitionFile, spec.Guid);
                    if (fileDefinition == null)
                        throw new InvalidOperationException("共享参数文件缺少 GUID " + spec.Guid + "（" + spec.Name + "）。");
                    if (!string.Equals(fileDefinition.Name, spec.Name, StringComparison.Ordinal))
                        throw new InvalidOperationException("共享参数 GUID " + spec.Guid + " 的名称不匹配，期望“" + spec.Name + "”，实际“" + fileDefinition.Name + "”。");
                    if (fileDefinition.UserModifiable != spec.UserModifiable)
                        throw new InvalidOperationException("共享参数“" + spec.Name + "”的用户可编辑设置与插件规则不一致。");

                    EnsureGenericModelInstanceBinding(doc, fileDefinition, spec);
                }
            }
            finally
            {
                doc.Application.SharedParametersFilename = originalFile;
            }
        }

        /// <summary>
        /// Writes the eight user-facing values to one maintenance DirectShape by GUID.
        /// Null MaintenanceConclusion/ProfessionalNote values preserve an existing
        /// user's confirmation. Null DecisionNote preserves the current generated reason.
        /// </summary>
        public static void ApplyToDirectShape(DirectShape shape, MaintenanceParameterValues values)
        {
            if (shape == null) throw new ArgumentNullException("shape");
            if (values == null) throw new ArgumentNullException("values");
            RequireModifiableDocument(shape.Document);
            if (shape.Category == null || shape.Category.BuiltInCategory != BuiltInCategory.OST_GenericModel)
                throw new ArgumentException("维修可达参数只能赋给常规模型 DirectShape。", "shape");

            SetRequiredText(shape, ElementNameGuid, ParameterElementName, values.ElementName);
            SetRequiredText(shape, CeilingGroupGuid, ParameterCeilingGroup, values.CeilingGroup);
            SetRequiredText(shape, EntryGroupGuid, ParameterEntryGroup, values.EntryGroup);
            SetRequiredText(shape, ElementRoleGuid, ParameterElementRole, values.ElementRole);
            SetRequiredText(shape, MaintenanceTargetGuid, ParameterMaintenanceTarget, values.MaintenanceTarget);
            if (values.MaintenanceConclusion != null)
                SetRequiredText(shape, MaintenanceConclusionGuid, ParameterMaintenanceConclusion,
                    NormalizeConclusion(values.MaintenanceConclusion));

            SetOptionalText(shape, DecisionNoteGuid, ParameterDecisionNote, values.DecisionNote);
            SetOptionalText(shape, ProfessionalNoteGuid, ParameterProfessionalNote, values.ProfessionalNote);
        }

        /// <summary>
        /// Creates or refreshes CODEX-owned materials and parameter filters in a specified
        /// non-template 3D view.  Element overrides are deliberately not used.
        /// </summary>
        public static void EnsureViewPresentation(Document doc, View3D view)
        {
            RequireModifiableDocument(doc);
            if (view == null) throw new ArgumentNullException("view");
            Element viewFromDocument = doc.GetElement(view.Id);
            if (viewFromDocument == null ||
                !string.Equals(viewFromDocument.UniqueId, view.UniqueId, StringComparison.Ordinal))
                throw new ArgumentException("视图不属于指定文档。", "view");
            if (view.IsTemplate) throw new ArgumentException("请指定普通三维视图，不能指定视图样板。", "view");
            if (!view.AreGraphicsOverridesAllowed())
                throw new InvalidOperationException("指定的三维视图不允许图形替换。");

            FillPatternElement solidFill = FindSolidFill(doc);
            if (solidFill == null)
                throw new InvalidOperationException("项目中找不到实心填充图案，无法创建维修可达显示样式。");

            // Older prototypes used an unversioned prefix and no ownership marker.
            // Leave those project resources untouched, but remove their exact filters
            // from this dedicated presentation view so they cannot override v1 colors.
            foreach (ElementId appliedFilterId in view.GetFilters().ToList())
            {
                FilterElement legacy = doc.GetElement(appliedFilterId) as FilterElement;
                if (legacy != null &&
                    legacy.Name.StartsWith(LegacyResourcePrefix, StringComparison.Ordinal) &&
                    !legacy.Name.StartsWith(ResourcePrefix, StringComparison.Ordinal))
                    view.RemoveFilter(appliedFilterId);
            }

            foreach (MaterialSpec materialSpec in MaterialSpecs)
                EnsureMaterial(doc, materialSpec, solidFill.Id);

            ElementId genericModelCategoryId = new ElementId((long)BuiltInCategory.OST_GenericModel);
            IList<ElementId> categories = new List<ElementId> { genericModelCategoryId };
            foreach (FilterSpec spec in FilterSpecs)
            {
                ElementId parameterId = GetSharedParameterElementId(doc, spec.ParameterGuid, spec.Name);
                FilterRule rule = spec.Contains
                    ? ParameterFilterRuleFactory.CreateContainsRule(parameterId, spec.MatchValue)
                    : ParameterFilterRuleFactory.CreateEqualsRule(parameterId, spec.MatchValue);
                ElementFilter elementFilter = new ElementParameterFilter(rule);
                ParameterFilterElement filter = EnsureParameterFilter(doc, spec.Name, categories, elementFilter);
                if (!view.IsFilterApplied(filter.Id)) view.AddFilter(filter.Id);
                view.SetFilterVisibility(filter.Id, true);
                view.SetIsFilterEnabled(filter.Id, true);
                view.SetFilterOverrides(filter.Id,
                    spec.IsConclusion
                        ? CreateConclusionOverrides(spec.Color, solidFill.Id)
                        : CreateRoleOverrides(
                            spec.Color,
                            solidFill.Id,
                            spec.FillSurfaces,
                            spec.Transparency));
            }
        }

        /// <summary>
        /// Returns a CODEX material suitable for geometry creation.  The presentation
        /// resources must already have been ensured inside the current transaction.
        /// </summary>
        public static ElementId GetConclusionMaterialId(Document doc, string conclusion)
        {
            string normalized = NormalizeConclusion(conclusion);
            string name = ResourcePrefix + "材质_" + normalized;
            Material material = FindMaterial(doc, name);
            if (material == null)
                throw new InvalidOperationException("缺少维修可达材质“" + name + "”，请先调用 EnsureViewPresentation。");
            if (!IsOwnedResource(material))
                throw new InvalidOperationException("同名材质“" + name + "”不属于 OpenRevit，拒绝接管。");
            return material.Id;
        }

        private static void EnsureGenericModelInstanceBinding(Document doc, ExternalDefinition fileDefinition, ParameterSpec spec)
        {
            Definition existingDefinition;
            Binding existingBinding;
            FindBindingByGuid(doc, spec.Guid, out existingDefinition, out existingBinding);

            if (existingDefinition != null)
            {
                if (!string.Equals(existingDefinition.Name, spec.Name, StringComparison.Ordinal))
                    throw new InvalidOperationException("项目中 GUID " + spec.Guid + " 已被参数“" + existingDefinition.Name + "”使用，不能安全替换为“" + spec.Name + "”。");
                InstanceBinding instanceBinding = existingBinding as InstanceBinding;
                if (instanceBinding == null)
                    throw new InvalidOperationException("共享参数“" + spec.Name + "”已以类型参数绑定，不会自动破坏性地改为实例参数。");

                Category genericModel = doc.Settings.Categories.get_Item(BuiltInCategory.OST_GenericModel);
                if (instanceBinding.Categories.Contains(genericModel)) return;

                CategorySet expanded = doc.Application.Create.NewCategorySet();
                foreach (Category category in instanceBinding.Categories) expanded.Insert(category);
                expanded.Insert(genericModel);
                bool rebound = doc.ParameterBindings.ReInsert(
                    existingDefinition,
                    doc.Application.Create.NewInstanceBinding(expanded),
                    GroupTypeId.IdentityData);
                if (!rebound)
                    throw new InvalidOperationException("无法将共享参数“" + spec.Name + "”的既有绑定安全扩展到常规模型。");
                return;
            }

            ThrowIfNameIsBoundToDifferentGuid(doc, spec.Name, spec.Guid);
            CategorySet categories = doc.Application.Create.NewCategorySet();
            categories.Insert(doc.Settings.Categories.get_Item(BuiltInCategory.OST_GenericModel));
            bool inserted = doc.ParameterBindings.Insert(
                fileDefinition,
                doc.Application.Create.NewInstanceBinding(categories),
                GroupTypeId.IdentityData);
            if (!inserted)
                throw new InvalidOperationException("无法将共享参数“" + spec.Name + "”绑定到常规模型实例。");
        }

        private static ExternalDefinition FindExternalDefinition(DefinitionFile file, Guid guid)
        {
            foreach (DefinitionGroup group in file.Groups)
            {
                foreach (Definition definition in group.Definitions)
                {
                    ExternalDefinition external = definition as ExternalDefinition;
                    if (external != null && external.GUID == guid) return external;
                }
            }
            return null;
        }

        private static void FindBindingByGuid(Document doc, Guid guid, out Definition definition, out Binding binding)
        {
            definition = null;
            binding = null;
            DefinitionBindingMapIterator iterator = doc.ParameterBindings.ForwardIterator();
            iterator.Reset();
            while (iterator.MoveNext())
            {
                Definition candidate = iterator.Key;
                Guid? candidateGuid = GetDefinitionGuid(doc, candidate);
                if (!candidateGuid.HasValue || candidateGuid.Value != guid) continue;
                definition = candidate;
                binding = iterator.Current as Binding;
                return;
            }
        }

        private static Guid? GetDefinitionGuid(Document doc, Definition definition)
        {
            ExternalDefinition external = definition as ExternalDefinition;
            if (external != null) return external.GUID;
            InternalDefinition internalDefinition = definition as InternalDefinition;
            if (internalDefinition == null) return null;
            SharedParameterElement shared = doc.GetElement(internalDefinition.Id) as SharedParameterElement;
            return shared == null ? (Guid?)null : shared.GuidValue;
        }

        private static void ThrowIfNameIsBoundToDifferentGuid(Document doc, string name, Guid intendedGuid)
        {
            DefinitionBindingMapIterator iterator = doc.ParameterBindings.ForwardIterator();
            iterator.Reset();
            while (iterator.MoveNext())
            {
                Definition candidate = iterator.Key;
                if (!string.Equals(candidate.Name, name, StringComparison.Ordinal)) continue;
                Guid? existingGuid = GetDefinitionGuid(doc, candidate);
                if (!existingGuid.HasValue || existingGuid.Value != intendedGuid)
                    throw new InvalidOperationException("项目中已有同名但 GUID 不同的参数“" + name + "”，为避免误写已停止绑定。");
            }
        }

        private static void SetRequiredText(Element element, Guid guid, string name, string value)
        {
            Parameter parameter = element.get_Parameter(guid);
            if (parameter == null)
                throw new InvalidOperationException("常规模型缺少共享参数“" + name + "”，请先完成参数绑定。");
            if (parameter.IsReadOnly)
                throw new InvalidOperationException("共享参数“" + name + "”对 API 不可写。");
            if (!parameter.Set(value ?? string.Empty))
                throw new InvalidOperationException("共享参数“" + name + "”赋值失败。");
        }

        private static void SetOptionalText(Element element, Guid guid, string name, string value)
        {
            if (value == null) return;
            SetRequiredText(element, guid, name, value);
        }

        private static string NormalizeConclusion(string value)
        {
            if (string.Equals(value, ConclusionPending, StringComparison.Ordinal)) return ConclusionPending;
            if (string.Equals(value, ConclusionMaintainable, StringComparison.Ordinal)) return ConclusionMaintainable;
            if (string.Equals(value, ConclusionNotMaintainable, StringComparison.Ordinal)) return ConclusionNotMaintainable;
            if (string.Equals(value, ConclusionError, StringComparison.Ordinal)) return ConclusionError;
            return ConclusionError;
        }

        private static ElementId GetSharedParameterElementId(Document doc, Guid guid, string ownerName)
        {
            SharedParameterElement parameter = SharedParameterElement.Lookup(doc, guid);
            if (parameter == null)
                throw new InvalidOperationException("缺少用于过滤器“" + ownerName + "”的共享参数，请先调用 EnsureSharedParameters。");
            return parameter.Id;
        }

        private static ParameterFilterElement EnsureParameterFilter(
            Document doc,
            string name,
            IList<ElementId> categories,
            ElementFilter elementFilter)
        {
            FilterElement nameCollision = new FilteredElementCollector(doc)
                .OfClass(typeof(FilterElement))
                .Cast<FilterElement>()
                .FirstOrDefault(x => string.Equals(x.Name, name, StringComparison.Ordinal));
            ParameterFilterElement filter = nameCollision as ParameterFilterElement;
            if (nameCollision != null && filter == null)
                throw new InvalidOperationException("项目中已有非参数过滤器使用 CODEX 保留名称“" + name + "”。");

            if (filter == null)
            {
                filter = ParameterFilterElement.Create(doc, name, categories, elementFilter);
                MarkOwnedResource(filter, "ParameterFilter");
                return filter;
            }

            if (!IsOwnedResource(filter))
                throw new InvalidOperationException(
                    "项目中已有同名参数过滤器“" + name + "”，但它不属于 OpenRevit；为保护用户资源，本次拒绝覆盖。");

            filter.SetCategories(categories);
            // False means the existing rules were already equivalent, not failure.
            filter.SetElementFilter(elementFilter);
            return filter;
        }

        private static OverrideGraphicSettings CreateRoleOverrides(
            Color color,
            ElementId solidFillId,
            bool fillSurfaces,
            int transparency)
        {
            OverrideGraphicSettings graphics = new OverrideGraphicSettings();
            graphics.SetProjectionLineColor(color);
            graphics.SetProjectionLineWeight(6);
            graphics.SetCutLineColor(color);
            graphics.SetCutLineWeight(6);
            if (fillSurfaces)
            {
                graphics.SetSurfaceForegroundPatternId(solidFillId);
                graphics.SetSurfaceForegroundPatternColor(color);
                graphics.SetSurfaceForegroundPatternVisible(true);
                graphics.SetCutForegroundPatternId(solidFillId);
                graphics.SetCutForegroundPatternColor(color);
                graphics.SetCutForegroundPatternVisible(true);
                graphics.SetSurfaceTransparency(Math.Max(0, Math.Min(100, transparency)));
            }
            return graphics;
        }

        private static OverrideGraphicSettings CreateConclusionOverrides(Color color, ElementId solidFillId)
        {
            OverrideGraphicSettings graphics = new OverrideGraphicSettings();
            graphics.SetSurfaceForegroundPatternId(solidFillId);
            graphics.SetSurfaceForegroundPatternColor(color);
            graphics.SetSurfaceForegroundPatternVisible(true);
            graphics.SetCutForegroundPatternId(solidFillId);
            graphics.SetCutForegroundPatternColor(color);
            graphics.SetCutForegroundPatternVisible(true);
            graphics.SetSurfaceTransparency(12);
            return graphics;
        }

        private static FillPatternElement FindSolidFill(Document doc)
        {
            return new FilteredElementCollector(doc)
                .OfClass(typeof(FillPatternElement))
                .Cast<FillPatternElement>()
                .FirstOrDefault(x => x.GetFillPattern().IsSolidFill);
        }

        private static void EnsureMaterial(Document doc, MaterialSpec spec, ElementId solidFillId)
        {
            Material material = FindMaterial(doc, spec.Name);
            if (material == null)
            {
                material = doc.GetElement(Material.Create(doc, spec.Name)) as Material;
                if (material != null) MarkOwnedResource(material, "Material");
            }
            if (material == null)
                throw new InvalidOperationException("无法创建材质“" + spec.Name + "”。");
            if (!IsOwnedResource(material))
                throw new InvalidOperationException(
                    "项目中已有同名材质“" + spec.Name + "”，但它不属于 OpenRevit；为保护用户资源，本次拒绝覆盖。");

            material.Color = spec.Color;
            material.Transparency = spec.Transparency;
            material.UseRenderAppearanceForShading = false;
            material.SurfaceForegroundPatternId = solidFillId;
            material.SurfaceForegroundPatternColor = spec.Color;
            material.CutForegroundPatternId = solidFillId;
            material.CutForegroundPatternColor = spec.Color;
        }

        private static Material FindMaterial(Document doc, string name)
        {
            return new FilteredElementCollector(doc)
                .OfClass(typeof(Material))
                .Cast<Material>()
                .FirstOrDefault(x => string.Equals(x.Name, name, StringComparison.Ordinal));
        }

        private static bool IsOwnedResource(Element element)
        {
            if (element == null) return false;
            Schema schema = Schema.Lookup(ResourceOwnershipSchemaGuid);
            if (schema == null) return false;
            Entity entity = element.GetEntity(schema);
            if (!entity.IsValid()) return false;
            Field ownerField = schema.GetField("OwnerId");
            return ownerField != null && string.Equals(
                entity.Get<string>(ownerField),
                ResourceOwnerId,
                StringComparison.Ordinal);
        }

        private static void MarkOwnedResource(Element element, string resourceKind)
        {
            if (element == null) throw new ArgumentNullException("element");
            Schema schema = GetOrCreateResourceOwnershipSchema();
            var entity = new Entity(schema);
            entity.Set(schema.GetField("OwnerId"), ResourceOwnerId);
            entity.Set(schema.GetField("ResourceKind"), resourceKind ?? string.Empty);
            element.SetEntity(entity);
        }

        private static Schema GetOrCreateResourceOwnershipSchema()
        {
            Schema existing = Schema.Lookup(ResourceOwnershipSchemaGuid);
            if (existing != null) return existing;

            var builder = new SchemaBuilder(ResourceOwnershipSchemaGuid);
            builder.SetSchemaName("OpenRevitMaintenanceResourceOwnership");
            builder.SetReadAccessLevel(AccessLevel.Public);
            builder.SetWriteAccessLevel(AccessLevel.Public);
            builder.AddSimpleField("OwnerId", typeof(string));
            builder.AddSimpleField("ResourceKind", typeof(string));
            return builder.Finish();
        }

        private static void RequireModifiableDocument(Document doc)
        {
            if (doc == null) throw new ArgumentNullException("doc");
            if (!doc.IsModifiable)
                throw new InvalidOperationException("请在调用 MaintenanceParameterService 前启动 Revit 事务。");
        }
    }
}
